spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.224:3306/supermarket?characterEncoding=UTF8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 20
      min-idle: 10
      max-wait-millis: 600000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
    dbcp:
      max-active: 50
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 20
        max-concurrency: 20
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 5
        max-interval: 10000
        multiplier: 1.0
mybatis:
  mapper-locations: classpath:mapper/*.xml
redis:
  password:
  poolMaxTotal: 150
  poolMaxIdel: 50
  poolMaxWait: 10
  timeout: 10
  port: 6379
  host: localhost